---
- name: Create samba user
  user:
    name: "{{ fsd_cloud_disk_user_name }}"
    state: "present"

- name: 创建 samba cloud disk 目录
  file:
    path: "{{ fsd_cloud_disk_root_path }}/samba"
    state: "directory"
    mode: "0777"
    recurse: yes

- name: Create disksize file
  file:
    path: "{{ fsd_cloud_disk_root_path }}/samba/disksize"
    mode: "0777"
    state: touch

- name: Copy samba shell scribe
  template:
    src: "diskSize.sh.j2"
    dest: "{{ fsd_cloud_disk_root_path }}/samba/diskSize.sh"
    mode: "0777"
  become: true

- name: Cope samba config file
  template:
    src: "smb.conf.j2"
    dest: "/etc/samba/smb.conf"
    mode: "0755"
  become: true

- name: Restart samba service
  service:
    name: "{{ item }}"
    state: "restarted"
    enabled: true
  become: True
  with_items:
    - "nmbd"
    - "smbd"
  when: 
    - ansible_distribution == "Ubuntu"

- name: Restart samba service
  service:
    name: "{{ item }}"
    state: "restarted"
    enabled: true
  become: True
  with_items:
    - "nmb"
    - "smb"
  when: 
    - ansible_distribution == "openEuler"